### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [Parchive/par2cmdline#138]
A new version soon?
Last is from 2017.

**Comment by SethosII** [comment]
This would bring the fix for https://github.com/Parchive/par2cmdline/issues/118 in a official version.

**Comment by thezoggy** [comment]
any update?

**Comment by mdnahas** [comment]
What do you mean by "new version"?  Where are you getting your binary from?

**Comment by Neustradamus** [comment]
Current last is 0.8.0 (2017-12-11): https://github.com/Parchive/par2cmdline/releases
More than 2 years...

**Comment by mdnahas** [comment]
@BlackIkeEagle Ike, do you want to take this?

**Comment by BlackIkeEagle** [comment]
Yes I'll make a new release somewhere this week

**Comment by thezoggy** [comment]
@Safihre we wanna roll a new sab update once it comes out? (after testing)

**Comment by Safihre** [comment]
@thezoggy we don't include `par2cmdline`, for Windows we use MultiPar and for MacOS `par2-sl`. @jcfp includes it in the PPA as a separate package and other package-providers for NAS-systems e.g. build `par2cmdline` themselves. So it's up to them :)

**Comment by thezoggy** [comment]
yes i know we dont include it, but its been awhile since we did a build and figure there might be some options we need to detect/correct for on the new version. plus just to get one last py2 version out the door before we go py3 only

**Comment by BlackIkeEagle** [comment]
0.8.1 was just released

**Comment by mdnahas** [comment]
Thanks, Ike!

**Comment by Safihre** [comment]
That's a long change-log.. What really changed? Since it's only a x.x.1 release.

**Comment by mdnahas** [comment]
There's a lot of commits because I refactored code, added unit tests, and added testing with Valgrind and Wine.

Most of the changes are bug fixes.  I think someone wanted a new release because the new code handle larger files or larger block sizes correctly.    

The big change is that we can now compile into a library for inclusion with other programs.  Users might see some better performance because it now checks the amount of physical RAM before deciding how much to allocate.

**Comment by Neustradamus** [comment]
@BlackIkeEagle: Thanks :)
