### ISSUE TITLE
A potential Data Race

### ISSUE THREAD

**Issue by PeimingLiu** [Parchive/par2cmdline#140]
Hi,

We developed a static data race detection tool for OpenMP programs, and we tested our tool on your program. Here is one race condition detected by our tool.

Between `src/par2creator.cpp@338`
``` 
 336|  {
 337|#ifdef _OPENMP
>338|    if (openfailed)
 339|      continue;
 340|#endif
```
and `src/par2creator.cpp@362`
```
 360|      delete sourcefile;
 361|#ifdef _OPENMP
>362|      openfailed = true;
 363|      continue;
 364|#else
```

Could you please confirm it with us?

Thanks!

**Comment by mdnahas** [comment]
Thanks for doing static checks on our code!   They're a great way to find bugs and we don't have time to run every good static checker on our code.

I don't think this case is a race condition.  The write on line 362 must be read by line 384.  The read that you identified, which is on line 338, is an optimization.  Basically, if any iteration of the loop encounters an error, line 338 allows other iterations to skip the work they were assigned.  This allows the loop to end quicker if it encounters an error.  If the read on line 338 gets a stale value, the code is slower but still correct.  

I'm not an OPENMP expert.  I encourage you to take a look at the code and let me know if I'm not seeing something.  Also, if there's a better way to write the loop so that it does the same thing and doesn't trip up your static checker, please let us know.

Mike

**Comment by PeimingLiu** [comment]
So sorry for the late reply... (as I did not receive notification from Github).

First of all, I think you are correct in some sense. In most cases, developers do not consider the reported case as a data race. It does not, in general, result in incorrect results.

However, I believe it is a true data race and potentially it can lead to undefined behavior. The code pattern is very similar to a code example listed in the [blog posted by Intel](https://software.intel.com/en-us/blogs/2013/01/06/benign-data-races-what-could-possibly-go-wrong)

```
int stop;

stop = 1; // Says other threads to stop.

// Other threads:

while (!stop) {
   // do something
}

```

I think you can avoid it by making variable `openfailed` atomic. But I do agree with you that this pair of race is benign in most cases.
