### ISSUE TITLE
[0.8.1] test failure in unit_tests on s390x, powerpc

### ISSUE THREAD

**Issue by jcfp** [Parchive/par2cmdline#143]
Uploaded 0.8.1 to a [Launchpad PPA](https://launchpad.net/~jcfp/+archive/ubuntu/sab-addons/+packages) just now, and got build failures on s390x and powerpc. Available architectures differ slightly per Ubuntu release on that service, but the issue seems to be failure to pass the new unit_tests on anything big-endian. All other build are fine (i386, amd64, arm64, armhf, ppc64el; all little-endian).

Example log attached (ubuntu focal/20.04 s390x), other examples of failed builds is anything recent [here](https://launchpad.net/~jcfp/+archive/ubuntu/sab-addons/+builds?build_text=&build_state=failed).
[buildlog_ubuntu-focal-s390x.par2cmdline_0.8.1-0ubuntu1~jcfp1~20.04_BUILDING.log](https://github.com/Parchive/par2cmdline/files/4188227/buildlog_ubuntu-focal-s390x.par2cmdline_0.8.1-0ubuntu1.jcfp1.20.04_BUILDING.log)

**Comment by mdnahas** [comment]
I wrote the test that is failing.   For the record, it's in reedsolomon_test.cpp, "test4<Galois16,u16>(10, expected_bases16)"

The test pretends there are 10 input blocks ("NUM_IN") and 1 recovery block ("NUM_REC"), each 1024 bytes long ("BUF_SIZE").  These are all stored in data[11][BUF_SIZE], with the input blocks occupying data[0] through data[9] and the recovery block in data[10].  

The test zeroes out the input blocks and then writes a 16-bit galois field value of 1 into the 1st and 2nd bytes of the first input block, and into the 3rd and 4th bytes of the second input block, 5th and 6th bytes of the third, etc.  It then generates the recovery block using many calls to ReedSolomon<Galois16>.  When that happens, those 1s are multiplied by the coefficients for each input block. So the 1st and 2nd bytes of the recovery block holds the coefficient for the first input block, the 3rd and 4th bytes have the coefficient for the second input block, etc.  Those values are checked against the expected values passed to the function.  

I think I found the bug.  I assumed the conversion of Galois16 to uint16 would handle the endianness conversion.  It does not.  The endianness is handled internally to rs_creator.  I think the fix is to do endian conversion explicitly inside the test.  I'll try to get some code out tomorrow.

**Comment by jcfp** [comment]
Thanks for the quick response. Backported #144 to the PPA package and the build is passing on all archs now.

**Comment by BlackIkeEagle** [comment]
@jcfp Do you know if we would switch to github actions we could cover these issues better?

**Comment by jcfp** [comment]
> @jcfp Do you know if we would switch to github actions we could cover these issues better?

Ideally you'd want to test against a range of hardware features and compiler versions. This particular issue would only have been caught by having big-endian as part of the ci setup; afaik travis can only do so via crossbuilding, not familiar with github actions to know if they are better in that respect.
