### ISSUE TITLE
0.8.1 build fails in Cygwin

### ISSUE THREAD

**Issue by andrew-schulman** [Parchive/par2cmdline#146]
When I try to build version 0.8.1 in Cygwin x86_64, the build fails with "‘strcasecmp’ was not declared in this scope":
```
In file included from /home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/commandline.cpp:24:
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/commandline.cpp: In member function ‘bool CommandLine::ReadArgs(int, const char* const*)’:
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/commandline.h:43:17: error: ‘strcasecmp’ was not declared in this scope; did you mean ‘strncmp’?
   43 | #define stricmp strcasecmp
      |                 ^~~~~~~~~~
```
I can work around this by adding `#include <strings.h>` to commandline.h. But then the build fails again, with " ‘fseeko’ was not declared in this scope":
```
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/diskfile.cpp: In member function ‘bool DiskFile::Create(std::string, u64)’:
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/diskfile.cpp:446:16: error: ‘fseeko’ was not declared in this scope; did you mean ‘fseek’?
  446 | # define fseek fseeko
      |                ^~~~~~
```
I tried adding `#include <stdio.h>` in diskfile.ccp, but that didn't fix the error. And I don't really know what I'm doing there anyway.

The build succeeded fine with 0.8.0.

**Comment by mdnahas** [comment]
Hi Andrew.  Yeah, that's probably my fault.  I reorganized all those headers so that Par2 could be used as a library. 

One of your problems is a bug.  You hit "#define stricmp strcasecmp" in commandline.h.  That code should match the stricmp code in libpar2internal.h, and it doesn't.  It should be:

#if !HAVE_STRICMP
#  if HAVE_STRCASECMP
#    define stricmp strcasecmp
#  endif
#endif

Can replace "#define stricmp strcasecmp" in commandline.h with the above code and tell me if it works?


You second problem was hitting "# define fseek fseeko" in diskfile.cpp.  I changed the ifdefs in that file too.  Par2cmdline now uses the official "_WIN32" to check for Windows, instead of "WIN32".  But, since you're hitting the line "# define fseek fseeko", it looks like you're compiling the POSIX or UNIX code like I'd expect for Cygwin.  So that's good.

But, the ifdefs surrounding the line "#define fseek fseeko" in this file haven't changed since the last version.  I'm not sure how "HAVE_FSEEKO" is getting set, when you don't have fseeko().

StackOverflow says Cygwin is weird when it comes to fseeko().
[Link](https://stackoverflow.com/questions/30867831/portable-support-for-large-files)
But this goes beyond that, because "HAVE_FSEEKO" is getting set.

StackOverflow suggests a quick fix is compiling with the --std=gnu++11 option.
[Link](https://stackoverflow.com/questions/20573123/alternatives-to-fseeko-for-cygwin)

Can you try replacing "-std=c++11" in Makefile.am with "--std=gnu++11" or "-std=gnu++11" and seeing if it compiles?

**Comment by andrew-schulman** [comment]
So I added this patch:

```
diff -urN par2cmdline-0.8.1.orig/src/commandline.h par2cmdline-0.8.1/src/commandline.h
--- par2cmdline-0.8.1.orig/src/commandline.h    2020-02-09 09:53:55.000000000 -0500
+++ par2cmdline-0.8.1/src/commandline.h 2020-03-11 12:14:35.809817300 -0400
@@ -40,7 +40,11 @@
 #else

 #include <string.h>
-#define stricmp strcasecmp
+#if !HAVE_STRICMP
+#  if HAVE_STRCASECMP
+#    define stricmp strcasecmp
+#  endif
+#endif

 #endif

```
But the build still fails with:
```
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/commandline.cpp: In member function ‘bool CommandLine::ReadArgs(int, const char* const*)’:
/home/ASchulma/dev/cygwin/par2/par2-0.8.1-1.x86_64/src/par2cmdline-0.8.1/src/commandline.cpp:228:31: error: ‘stricmp’ was not declared in this scope; did you mean ‘strncmp’?
  228 |   if (name.size() > 4 && 0 == stricmp(".exe", name.substr(name.length()-4).c_str()))
      |                               ^~~~~~~
      |                               strncmp
```
I'm scratching my head over this, because the `#if` conditions should be satisfied:
```
$ grep -e '(STRCASECMP|STRICMP)' config.h
#define HAVE_STRCASECMP 1
/* #undef HAVE_STRICMP */
```
Please let me know what other information I can provide. I did add the `--std=gnu++11` flag to the compilation, but I haven't been able to test that yet.

**Comment by mdnahas** [comment]
It feels like something is messed up with your includes.  Let me know if --std=gnu++11 (or -std=gnu++11 ?) fixes it.

**Comment by andrew-schulman** [comment]
> It feels like something is messed up with your includes. Let me know if --std=gnu++11 (or -std=gnu++11 ?) fixes it.

OK, yes. WIth no patches, just `-std=gnu++11` fixes the problem. 

I'll add it to the Cygwin build script, so that should take care of it in the future. Thanks!

**Comment by mdnahas** [comment]
@andrew-schulman Thanks!
