### ISSUE TITLE
Understanding par2cmdline performance

### ISSUE THREAD

**Issue by rdiez** [Parchive/par2cmdline#151]
I have a number of computers running Linux and Windows (Cygwin), and I have written a script to "comfortably" backup my data to an external USB disk (rotational with 4 TB):

https://github.com/rdiez/Tools/blob/master/BackupFiles/backup.sh

I run the script every now and then, and afterwards I rotate the USB disks and make sure one of them is always outside my home.

The script compresses and encrypts files with 7z (multivolume 7z.001, 7z.002, and so on). I wanted to add some redundancy in case some sectors get corrupted, and I could not find anything better than par2cmdline. I could try to do incremental backups, or investigate some other filesystem that provided encryption and redundancy on its own, but I could not find anything practicable yet for external rotating disks with different operating systems. Using 7z and par2 keeps it simple and easy.

The trouble is, the backup takes ages, especially the par2 phase, and I am looking for a way to accelerate it.

I am testing a smallish backup with a total 7z + par2 size of 12.1 GiB. There are 6 7z files, each weights 2 GiB. I can read the complete 7z and par2 files to /dev/null in 3 minutes. The external USB 3.0 disk delivers a read performance of 70 MiB/s.

Verifying with "par2 verify -q" takes 7 minutes and my Ubuntu 18.04.4 shows 33 % CPU load. My laptop has an Intel Core i5-8265U CPU @ 1.60GHz, with 4 cores + hyperthreading.

I tried adding argument -t9 to increase parallel processing, but that made little difference. The CPU load does not increase. The man page does warn about it:

"Hashing portion (file verification and creation stages) of the code can't be parallelized without processing multiple files simultaneously. The 2 file/thread default is a good choice for HDDs, using more threads can result in worse performance. Four or more threads can be used for better performance with SSDs."

I would like to understand how par2cmdline performs. If reading the files takes 3 minutes, and verifying the par2 files takes 7 minutes, what are those extra 4 minutes needed for?

Given that the CPU is not maxed out, is there a way to parallelise more? Would it be better to create more 7z.001, 7z.002, etc. files with smaller sizes?

Does par2cmdline need to seek often, so there is no way to make it faster on rotational drives? Or does it mostly read sequentially? Does it need to read the same data several times?

When generating the backup, I need to create the 7z files directly on the external backup disk, because the internal hard disk does not have space for both the source files and the 7z files, as most JPEGs do not compress well.

However, given that I am using a redundancy percentage of only 1 %, I could have par2cmdline read the 7z files from the external disk and write the resulting par2 files to the internal disk (which is often an SSD). Afterwards, I could just copy the par2 files from the internal to the external disk in a single sequential operation.

This way, par2cmdline would be reading from one disk and writing to another disk. Would it be much faster? That would probably only help if par2cmdline were doing much seeking around on the par2 files.

**Comment by animetosho** [comment]
I'm not that familiar with what verification exactly does (I imagine it's mostly bound by MD5/CRC32 computation, assuming all slices are present), but I can respond more about the process of creation:

* Note that create and verify have slightly different performance profiles. If you want to benchmark par2cmdline without the recovery computation time, try with the `-r0` parameter (i.e. generate no recovery)
* If the recovery data (in your case, 1% of 12GB = 120MB) cannot fit in memory, multiple read passes are needed to generate the recovery data which can fit in memory. If you're using the default 16MB limit, par2cmdline would need 120/16 = 8 read passes (+1 more for hashing). You can reduce the disk load by increasing the memory limit (ideally to hold all recovery data in memory, i.e. 120MB or more in the example)
* Reading should always be sequential, however, if multiple read passes are needed (due to memory limits), there will be a seek forward per slice read. To use the previous example, it would read 1/8th of each slice. If you're using the default of 2000 source blocks, 12GB/2000 = 6MB per slice, so the disk would read 0.75MB, skip 5.25MB to the next slice, read another 0.75MB etc
* In most cases, computation of recovery data takes the most time, and is CPU bound. However, if you've only got 1% redundancy, it may not be so true in your case (you didn't mention CPU usage during create)
* There are other PAR2 implementations which are faster: [MultiPar](https://github.com/Yutaka-Sawada/MultiPar) (Windows only, but works under Wine) and [ParPar](https://github.com/animetosho/ParPar) (create only, no verification/repair), however, these mostly focus on accelerating computation of recovery data (above point), so may not help as much. Still, as they're different implementations of PAR2, you can give them a try

> I tried adding argument -t9 to increase parallel processing

Is that `-t9` or `-T9`? Only the latter affects hashing/verification.

**Comment by rdiez** [comment]
First of all, thanks for your quick response.

There is a lot of stuff to think about in your first answer, so I'll probably be commenting further later on.

I completely missed the distinction between -t and -T. So I ran the same "par2 verify -q" test with both -t9 and -T9 at the same time, and there was no visible difference. CPU was not maxed out, and the time it took was about the same. So increasing -t and -T alone does not really help.

> I'm not that familiar with what verification exactly does (I imagine it's
> mostly bound by MD5/CRC32 computation, assuming all slices
> are present), but I can respond more about the process of creation:

Now that comment of yours is interesting:

1) Calculating MD5/CRC32 checksums on my laptop should be much faster than the external USB 3.0 hard disk, and all slices are actually present. Therefore, I assume that par2cmdline is not doing just that.

2) If par2cmdline were only verifying checksums, that would not be enough to check whether the par2 files themselves are intact. If some disk sectors get corrupted later on, and that corruption hits the main 7z backup files, I may then need a section of a par2 file that was perhaps corrupt since the beginning (!).

I am now worried. In order to completely verify my backup, I would have to recreate the .par2 files somewhere else and compare the old and the new par2 file set. It would be nice to get confirmation on this.

**Comment by rdiez** [comment]
Adding option "-m" when verifying with "par2 verify" (in the backup scenario I described above) does not change memory consumption in the "par2" process. The CPU remains low, so it does not really help. It actually seems to have no effect during verification.

**Comment by rdiez** [comment]
Adding option "-m" when creating, like shown below, does not affect memory consumption:

par2 create -r1 -t9 -T9 -m$((1 * 1024))

I wonder when option -m does have an effect!

Adding the -t9 -T9 -m options above yields no performance improvements on my external USB 3.0 disk. The time is the same, and the CPU load remains low. It takes 1 minute longer to create the par2 files than to read all files to /dev/null. Therefore, it seems that there is still room for improvement.

Creating the par2 files is actually faster than verifying them (!), 4 minutes against 7 minutes. Given their small size (with 1 % redundancy), I guess that rebuilding them somewhere else and comparing them would be faster than verifying, which is surprising.

**Comment by animetosho** [comment]
Your situation sounds weird - none of the tuning flags seem to be having any effect.

It may be worth observing disk activity, not just CPU, to see if that gives much info (`iostat` is a nice tool for this). Also check that there are threads that are processing (can check CPU usage per thread with something like `htop` and enabling userland threads to be displayed).  
You can also try with the `-v -v` flag to see if anything interesting is printed out, though I'm doubting that.

> that would not be enough to check whether the par2 files themselves are intact

PAR2 is self verified with MD5. As you only have 1% redundancy, the speed of the MD5 check on the PAR2 itself should be mostly negligible.  
PAR2 does duplicate critical packets to mitigate the risk of the PAR2 itself becoming corrupt.

> Adding option "-m" when verifying with "par2 verify"

`-m` parameter doesn't affect verification, only create and repair, as it specifies how much memory can be consumed whilst working with recovery data.

If you wish, you can try with a higher redundancy level (say 50%) to see if it ever uses more CPU and whether it helps the `-m` flag have more of an effect.

If you're willing to try, I'm also interested in how the other PAR2 tools, mentioned above, perform for you.

**Comment by rdiez** [comment]
That is quite some work. I was actually expecting to get some help here.  O8-)
I'll add it to my "to do" list, but no promises!

**Comment by rdiez** [comment]
Would you like to help me test par2's performance?

You can create the kind of test files I am using like this:

```
# Create 12 GiB of data distributed across 6 files.
FILE_SIZE_KB=$(( 2 * 1024 * 1024 )) && dd  bs=1024  count="$(( 6 * FILE_SIZE_KB ))"  if=/dev/urandom  status="none" | split -d --bytes="$FILE_SIZE_KB"K - TestData.bin
```
My laptop has 24 MiB of RAM, so the whole data fits in cache. If you want to include disk activity, you can empty the disk cache before each test under Linux like this:

`sudo bash -c "sync && echo 1 > /proc/sys/vm/drop_caches"`

I am creating the par2 files like this:

`time bash -c "par2 create -r1 RedundantData.par2 TestData.bin* && sync"`

If I add "-t1 -T1", CPU usage during creation drops, as expected. But adding "-t9 -T9" does not increase CPU usage. Can you confirm that on your system with par2 version 0.8.1 (the latest release)?

If I increase the redundancy percentage to 5% or 10%, then CPU usage does go up with "-t9 -T9", but it peaks at around 80 % and does not reach 100 %. If I specify only "-r10" and no -t or -T, then CPU usage does go up to 100 %, which does not make sense. My guess is that "create" is ignoring options "-t" and/or "-T".

I am verifying like this:

`time par2 verify RedundantData.par2`

Adding -t9 -T9 does make it much faster though, and CPU usage goes up to a full 100 %.

**Comment by animetosho** [comment]
I tried setting up something similar-ish to your setup, in terms of hardware performance. CPU is an AMD FX 8320, disk is a 2TB WD 5400RPM drive. Sequential read/write speed is around 60MB/s. For the tests, I emptied the disk cache before each run, to reduce the variability that caching might cause.

Using your create command, CPU usage is around 30%, but the disk is completely loaded, with read activity sitting around 60MB/s. In other words, the process is completely I/O bound. Time reports 3m57.772s real (7m38.105s user).  
Your result makes sense if you're seeing the same thing - increasing thread count won't help, because the disk is what's limiting performance.  
Adding `-t9 T9` doesn't make much difference, not surprisingly. Time reports 3m53.753s real (6m0.965s user).  
Adding `-t1 -T1`, as expected, limits performance, with CPU only using 1 core, and the disk only reading at around 30MB/s. Time reports 6m13.967s real (3m55.773s user).

Similarly, verification is disk bound, with CPU usage being around 7% during the process and the disk hitting its max read bandwidth. Time reports 3m21.485s real (1m39.003s user).  
With `-t9 T9` added, time reports 4m17.064s real (1m39.493s user)

Trying the disk speed itself, via `time bash -c "cat RedundantData.* TestData.* >/dev/null"`, I get a time of 3m10.150s.

The disk speed may seem faster than PAR2 creation time, despite the latter being disk bound. This isn't exactly unexpected - the 16MB memory limit does cause the I/O pattern to be a little inefficient. I think par2cmdline also runs an extra read pass to compute hashes, since it can't perform sequential hashing whilst chunking the input for calculating recovery.  
Furthermore, par2cmdline uses synchronous reads, so there'll be some switching inefficiencies (and some other overheads).

Thus, I tried your create command, but added `-m256`. Time reports 4m5.101s (7m35.459s user), so the inefficient read pattern isn't really affecting it much. As the block size is around 6MB, slicing it 6 times means 1MB read chunks, which probably works alright on spinning disks, so it not making much of a difference seems reasonable. Still, I'm not sure why the speed is *slower* in this case (though not by that much).

I also tested ParPar v0.3.2, which uses buffered async disk reads, via the command: `time bash -c "node bin/parpar -r1% -s6448900B -oRedundantData.par2 TestData.bin* && sync"`. Time reports 3m15.363s (2m26.423s user), which is much closer to the disk read speed. I'm not sure where the difference comes from, but par2cmdline's sync reads would be my guess.

> If I increase the redundancy percentage to 5% or 10%, then CPU usage does go up with "-t9 -T9", but it peaks at around 80 % and does not reach 100 %. If I specify only "-r10" and no -t or -T, then CPU usage does go up to 100 %, which does not make sense.

This makes some sense. Increasing redundancy increases CPU usage. If your 1% redundancy is disk bound, then increasing it makes the process more CPU bound. `-T9` is likely bad for spinning disks, so by using that, you're probably forcing the disk to seek a lot, limiting throughput, hence why you can't achieve 100% CPU load with it set.

Also keep in mind that you're still using the default 16MB memory limit, which will mess with the I/O read pattern with more recovery (cause more seeking). To remove that variable, you should increase the memory limit to fit all recovery in memory.

> Adding -t9 -T9 does make it much faster though, and CPU usage goes up to a full 100 %.

This is rather different from what you were reporting earlier - are you sure you dropped disk caches before this test?

**Comment by animetosho** [comment]
1. I don't know what your software would be displaying. I'd say check the RSS value for the process (if that's listed there), which should be a good measure. par2cmdline doesn't mmap files, and the `-m` setting doesn't affect file reading; it affects how much redundancy is held in memory at a time.
2. `-t` is the number of threads used for computing recovery. In your examples, the amount of redundancy created is very low, hence `-t` probably doesn't yield much of an effect. If you want to really see the effect, try something like `-r100` and you should see how `-t` affects processing speed.  
`-T` is as described. File hashing and recovery computation are different parts of the process.
3. In terms of recovery computation, each file is padded to the block size, then concatenated. Thus lots of small files is slightly less efficient as there's usually padding which recovery computation has to be done on, unless your chosen block size is an exact fraction of all the files.
4. The PAR2 format uses MD5 and CRC32 checksums. MD5 can only be computed sequentially. It's possible to mix chunked processing (to deal with memory limits) and hashing (ParPar implements this), but par2cmdline doesn't support doing that. Hashing is only performed concurrently with recovery computation, if all recovery can fit in memory (via the `-m` switch)

**Comment by rdiez** [comment]
Thanks again for your answers. Let's see whether I got this right:

a) par2 verification:

There is no recovery data calculation, only hashing, so options -t and -m have no effect.

CRC32 and MD5 hashing are much faster on my laptop CPU than my USB 3.0 hard disk, so the time it takes should be disk-bound. The trouble is that, according to my initial test results at the beginning of this GitHub issue, it is not by a great deal. I was seeing much longer times and 33 % CPU usage.

However, you are not seeing the same problem: Reading to /dev/null takes 3m10s on your test computer, and verifying takes 3m 21s, which is around 5 % longer. There is only 7 % CPU load.

Therefore, something is wrong: my measurements are incorrect, my USB disk is causing a high CPU load just by reading, or there is something else causing trouble.

Choosing a value for option -T is difficult:

- If you have a fast disk (like an SSD), or all 7z and par2 files fit in cache (unlikely), then you want -T to be as high as the number of CPU cores/threads.

- If you have a slow disk, anything above 2 will probably make it slower because of seeks. In your verification test, increasing from the default 2 to 9 increased the time by around 1 minute. So par2 must be seeking a lot.

If I could tell par2 to read the 7z files in very big chunks (say 100 MiB at a time), then reading 8 of them at the same time from an external USB 3.0 HDD would probably not decrease performance much, because there would be very few seeks (depending on how much the Linux kernel decides to interleave big disk read requests). In this case, choosing a big -T would help with SSDs, and not be a detriment for HDDs.

Unfortunately, there is no way I can tell par2 to read very big chunks for hashing purposes. Is that correct?


b) par2 creation:

There are 2 phases, hashing and calculation of recovery data.

b1) In order to hash, the 7z files are read sequentially. That should be I/O bound if the CPU is fast enough, because MD5 and CRC32 are not that heavy. This is similar to the verification operation.

b2) In order to calculate the recovery data:

Does par2 actually need to read the 7z files (the big test data files) again, if the complete recovery data does not fit in RAM? That would suddenly double the I/O time.

If the recovery data (the 1 %) does not fit in memory, multiple read scans will be needed in an interleaved I/O pattern. But those multiple reads only affect the recovery data (the 1 %). The 7z files (the big test datafiles) will not be read in an interleaved I/O pattern. Or will they?

In order to minimise seeks, which are slow on HDDs, increasing the size of the read chunks should help:

- I can increase the block size (option -s).
- I can increase memory usage (option -m), which means less slicing and therefore bigger chunks.

What are the drawbacks of increasing the block size? Can I set to something very big, like 512 MiB?

I will be testing that with RSS memory usage later with a much bigger, real-life backup.

**Comment by animetosho** [comment]
> There is no recovery data calculation, only hashing, so options -t and -m have no effect.

Correct.

> In this case, choosing a big -T would help with SSDs, and not be a detriment for HDDs.

Very likely correct.

> Unfortunately, there is no way I can tell par2 to read very big chunks for hashing purposes. Is that correct?

par2cmdline's read chunk size is tied to the [block size, if memory limit allows, otherwise a fraction of that](https://github.com/Parchive/par2cmdline/blob/cf23c38b0c9a3d5613073690807bd7cf1d479ae8/src/par2creator.cpp#L302-L314).

> There are 2 phases, hashing and calculation of recovery data.

Correct. Note that the 2 can be merged and processed concurrently, if par2cmdline isn't forced into chunking mode (due to memory limit).  
If you watch the progress as it's creating, you should be able to see the two phases separately, if the memory limit is too low - you'll get a percentage indicator during the 'Opening' phase (indicating the hashing pass), before 'Computing Reed Solomon matrix' is printed out. After that's displayed, the percentage displayed indicates recovery calculation.  
On the other hand, if the memory limit is high enough, there won't be a separate hash pass, as it'll be performed alongside recovery computation, so you should see 'Computing Reed Solomon matrix' very soon after starting.

> Does par2 actually need to read the 7z files (the big test data files) again, if the complete recovery data does not fit in RAM? That would suddenly double the I/O time.

Correct.

> The 7z files (the big test datafiles) will not be read in an interleaved I/O pattern. Or will they?

Yes, they will. Chunking mode means that both reads and writes need to be done in an interleaved pattern.

If it makes it easier to understand, imagine recovery computation simply being an XOR of all input blocks, to produce a recovery block. In other words, you read the first input block, then the second input block, and XOR the contents of the second onto the first. Repeat for the third and subsequent blocks. After you've gone through all blocks, write out this "XOR sum" out as the recovery block.  
An issue arises if you can't hold this block in memory. One way to handle this is to only read half of the first block, then half of the second block, XORing it into the first, and continuing. At the end of this, you'll have half a recovery block, which you can then write out. However, you'll need to repeat this process to handle the second half.  
par2cmdline effectively uses this approach if the memory limit is too low.

> What are the drawbacks of increasing the block size?

Less granularity in handling errors. PAR2 is block based, so a single error renders the entire block unusable. A 512MB block size means that a single bit flip renders the 512MB block it's in corrupt, meaning you'll need at least 512MB of redundant data to recover that.

**Comment by rdiez** [comment]
The information you wrote above is far too valuable to just stay in a GitHub issue like this. Should we try to incorporate it into par2's man page?

Other people should not go through all the trouble I am at the moment in order to understand how par2 performs, and last time I tried to read some document about the par2 file format I quickly gave up.

**Comment by animetosho** [comment]
If you're asking me, I don't maintain/contribute to this project, so it's not my decision to make.

Hopefully, this thread will help anyone who tries to search for it.

**Comment by animetosho** [comment]
> Does that really apply to the verification stage?

No, memory limit doesn't apply to verification as there's no recovery being computed.

Your strace pattern is interesting. I seem to get the same thing. Examining the reads in GDB suggest that it may be a libc thing, as `DiskFile::Read`/`fread` is always being asked the full block. Perhaps there's some optimisation around pages, or just fitting to 4KB; note that all requests to `read` are a multiple of 4KB, and as the block size isn't a 4KB multiple, it's probably trying to align the reads to fill an internal 4KB buffer.

I tried again, but set the block size to 4MB (i.e. a multiple of 4KB). The strace doesn't show tiny 4KB reads any more, so I guess this could be a little optimisation you could try.  
As a side thought, I wonder if it would be worthwhile for par2cmdline to just ditch the libc file I/O and make kernel calls directly. There's already special support for Windows, so compatibility outside POSIX is handled. The libc file I/O does provide buffering, but that's mostly useful for applications issuing tiny reads/writes, which isn't par2cmdline as it does its own buffering.

I also don't know much about disks over USB - maybe the protocol/interface doesn't handle interleaved reads as well as SATA. Sounds like you figured out the problem though - thanks for reporting back!

**Comment by rdiez** [comment]
I tried setting the block size to 4 MiB, which does generate clean strace reads.

Verifying with -T2 improves from 7 minutes to 6 minutes 40 seconds, so no drastic improvement.

Verifying with -T1 is still much faster, around 3 and a half minutes, so no improvement either compared to the other block size. I guess my USB 3.0 disk really hates interleaved reads.

What I do not understand is why verifying with -T4 or -T8 does not show interleaved reads with strace. All reads happen sequentially on the same file descriptor. I think I did see such interleaved access with the previous (default) block size I was using.

Anyway, I set the block size to a whopping 100 MiB, and that did not help either. On the contrary, it made both -T1 and -T2 slower.

My guess is that USB disks have a rather high latency per operation, and sequential reading from normal-sized blocks is the best way to access them. Or there is some other problem on my Linux laptop, because I verified on the same disk with my Windows 10 PC with Cygwin's par2 0.8.0, and there was no such a great difference:
-T1: 3 minutes, 6 seconds (186 seconds)
-T2: 3 minutes, 41 seconds (221 seconds)
On Windows, seeking around on an USB 3.0 disk also adds extra time, but not so much more. By the way, the filesystem is exFAT, but I do not think that it makes a difference.

**Comment by rdiez** [comment]
I have updated my file backup script with the par2 performance information I have learnt from your comments. It is here:

https://github.com/rdiez/Tools/blob/master/BackupFiles/backup.sh

If somebody wants to improve par2's man page, the information on this GitHub issue and the description in my script can serve as a starting point.

I am closing this issue, because I think I have everything I needed. Many thanks again for your help.

**Comment by rdiez** [comment]
One more thing I wanted to mention: If the total recovery data does not fit in memory, which is usually the case for large backups on big HDDs, then doing an extra read pass for hashing purposes really hurts performance.

[ParPar's benchmark page](https://github.com/animetosho/ParPar/blob/master/benchmarks/info.md) only focuses on CPU, but that probably does not do justice to ParPar.

If you have implemented mixing chunked processing (to deal with memory limits) and hashing in a single pass, then the benchmark page should mention this, so that it is clear what kind of performance losses par2 can incur.

**Comment by animetosho** [comment]
Doing benchmarks for disk is a little more problematic because RAM and disk cache come into play. There are different strategies employed by the clients, and trying to come up with parameters/options which is consistent between them gets tricky, so I felt that it was fairest to try to put them on the most level playing field and eliminate the disk aspect as much as possible. For common cases using 5-10% redundancy, CPU is usually the bottleneck, so I felt focusing on CPU was a decent proxy for performance.

I think you may be overestimating the benefit of merging the read pass though. If we ignore seeking cost (for simplicity), in par2cmdline's case, it will read the files twice. In other words, if your input is 1GB, it will read 2GB total (1GB for hashing, and multiple chunked passes totaling 1GB of reads).  
ParPar's read pattern can only eliminate one *chunked* read pass. That is, if *p* passes are needed to compute recovery, using the above example, ParPar would read 1GB/*p* less data overall. This is most beneficial if only 2 chunk passes are needed - par2cmdline would issue a total of 2GB of reads, whereas ParPar would issue 1.5GB reads. The benefit obviously decreases the more chunk passes are required (e.g. for 10 passes, it's 2GB vs 1.9GB).

Unfortunately, it's not possible to completely merge the two - chunked processing is optimal, I/O wise, for recovery computation, but the PAR2 format requires MD5 checksums for each file. MD5 cannot be computed in a chunked fashion, so it essentially requires a full sequential scan of the file.  
(there may be some edge cases which can be optimised better, e.g. if a large number of your input files fit within a block, but these are quite rare, difficult to manage, and, in my opinion, not worth the effort to try to optimise for)
