### ISSUE TITLE
Feature: TBB Support

### ISSUE THREAD

**Issue by druchoo** [Parchive/par2cmdline#27]
Any chance of getting TBB implemented?

http://chuchusoft.com/par2_tbb/index.html

**Comment by sbraz** [comment]
I have been using the old par2_tbb fork on a quadcore and the speed gains were substantial, I'd love to see this in the official version.

**Comment by Jhinta** [comment]
Where can i find this old fork? . also BlackIkeEagle doe you plant to add this ?

**Comment by jvhaarst** [comment]
http://chuchusoft.com/par2_tbb/

**Comment by Jhinta** [comment]
that one i cant get compiled on a armv7

2015-03-02 14:33 GMT+01:00 Jan van Haarst <notifications@github.com>:

**Comment by BlackIkeEagle** [comment]
@Jhinta you can check https://github.com/jkansanen/par2cmdline-mt for multithreading support

I will eventually ask if I can integrate his solution or see if I find another solution suitable for everyone.

The solution must be supporting threads and be as widely as possible usable so maybe intel tbb and openmp are not perfect solutions for this but usable if you want it now.

**Comment by Jhinta** [comment]
Tnx ,!! fully working .

2015-03-03 15:54 GMT+01:00 Ike Devolder <notifications@github.com>:

**Comment by epienbroek** [comment]
I've done some tests with this branch and it indeed causes all my CPU cores to be used during repair. I've also done some timing comparisons (verify and repair a set of files) against the various par2cmdline versions and here are the results:
```
par2-tbb:
real	2m13.139s
user	14m36.899s
sys	0m6.576s

par2cmdline 0.6.12:
real	5m29.718s
user	5m27.731s
sys	0m1.223s

par2cmdline 0.6.12 with OpenMP support:
real	3m34.538s
user	23m47.680s
sys	0m2.383s
```
The par2 set used in this tests consists of 1,7GB data files, 274 recovery blocks used for repair (blocksize 384000 bytes) and one of the data files (100MB) missing.

As package maintainer of the par2cmdline package in Fedora Linux (which is currently based on the par2-tbb fork) I'm currently researching whether it is a good idea to switch to this fork. The lack of threading support is currently the main blocking issue for me, but once these OpenMP changes are approved I'll make the switch to this fork as it is more reliable than the par2-tbb fork.

**Comment by sbraz** [comment]
What causes such a big difference  between the OpenMP and TBB versions?

**Comment by Safihre** [comment]
As a dev for SABnzbd, we would very much welcome a version with TBB, since it seems to outperform the OpenMT version by around 40%.
SABnzbd comes with the 0.4-TBB version by default on Windows and since all those years we never really had complaints about disk strain.
We are actually having more cases where the -N option would have been able to restore it, so having that + TBB would be very good for us :)

**Comment by jtwill** [comment]
I think that multipar is almost twice as fast as par2-tbb. Unfortunately, it is only released for Windows, and the author has no desire to port it to linux. I wonder how difficult it would be to port the multipar C code to linux.

https://www.livebusinesschat.com/smf/index.php?topic=5865.0

**Comment by Safihre** [comment]
I wanted to share these results while I am testing the best (Windows) solution for SABnzbd's Par2.
Test system is a Core i5-4200 with 2 cores and a Samsung 850 Pro SSD. 
**This is the average of 5 runs**
Unfortunately I can't build the par2cmdline-mt myself, but from the results below the 'winner' seems clear..
However the winner is, indeed, only available on Windows, which limits things for SABnzbd's purpose.
```
Data size: 3.28GB
Blocks 4485/4541 (156 missing)
464 Repair Blocks
---------------
VERIFY: 0.4 TBB x64
15.1515566 Seconds
VERIFY: par2cmdline 0.6.13 x86
41.3655667 Seconds
VERIFY: phpar2 version 1.4 x86
36.135805 Seconds
VERIFY: MultiPar 1.2.9.0 x64
16.8486896 Seconds
---------------
REPAIR: 0.4 TBB x64
195.0399945 Seconds
REPAIR: par2cmdline 0.6.13 x86
376.7458003 Seconds
REPAIR: phpar2 version 1.4 x86
186.3957853 Seconds
VERIFY: MultiPar 1.2.9.0 x64
75.6073459 Seconds
```

**Comment by Safihre** [comment]
Now a test-set not made by deleting RAR-files, but the way it actually comes from SABnzbd with missing articles in almost every file. 
Again, average of 5 runs:
```
Data size: 1.51GB
Blocks 2078/2164 (76 missing throughout all files)
213 Repair Blocks

---------------

VERIFY: 0.4 TBB x64
7.6988215 Seconds

VERIFY: par2cmdline 0.6.13 x86
20.1532372 Seconds

VERIFY: phpar2 version 1.4 x86
17.7300754 Seconds

VERIFY: MultiPar 1.2.9.0 x64
8.6438294 Seconds

---------------

REPAIR: 0.4 TBB x64
54.0448524 Seconds

REPAIR: par2cmdline 0.6.13 x86
100.3952918 Seconds

REPAIR: phpar2 version 1.4 x86
56.1471169 Seconds

REPAIR: MultiPar 1.2.9.0 x64
23.9853376 Seconds
```

**Comment by sbraz** [comment]
@Safihre Are you tweaking TBB with options like `-t0` or `-m10240` (if you have enough memory)? Using those will probably improve performance.

**Comment by Safihre** [comment]
No, just plain 'out of the box' ```par2.exe repair``` for all of them. Because this would also be how we would package it in SABnzbd.

**Comment by Jhinta** [comment]
@Safihre i gues 0.4 TBB x64 repair doent make use of the core's without -t0 and MultiPar by default use all cores .

i think 0.4 TBB x64 is still faster just make sure you have multi core enabled.
sabnzbd has -t0 by default muticore enabled as you only did par2 repair there is no multi core i belief.

**Comment by jtwill** [comment]
My copy of par2-tbb defaults to multicore. This is on linux, but I do not think it would be different on windows:
  -t<+<n>|0<n>|-<n>>: Threaded processing. The options are:
     -t+ to checksum and create/repair concurrently - uses all available logical CPUs - good for hard disk files - [default]
     -t0 to checksum serially but create/repair concurrently with all available logical CPUs - better for slow media such as CDs/DVDs
     -t- to checksum/create/repair serially - uses a single logical CPU - good for testing this program

I think multipar is faster because it is more optimized. In particular, I believe it takes advantage of special CPU instructions like SSE.

**Comment by Safihre** [comment]
Par2-tbb defaults to multicore, I just checked to make sure and it's using 100% CPU (so 4 threads). I ran it again with and without -t0 or -t+ and it averages to the same speed. SABnzbd also doesn't give any extra commands by default to any of them.

Actually MultiPar seems smart, it doesn't use 100% CPU because it knows I only have 2 real cores, not 4 so it only uses 3 threads so the system doesn't lock up.

**Comment by thezoggy** [comment]
@Safihre also multipar can use your GPU as well... i know back in the day it was buggy but wonder if its gotten stable / worth checking out.

**Comment by dermoth** [comment]
I guess i'll try par2tbb - FWIW, I always put files to create on SSD and CPU is the only bottleneck - I create parchives of many GB's (extending 16GB SD cards to the 25GB archival BD disk) and while my 4.2GHz core is kept very hot at 99% USER CPU the ssd is barely used (I had the opposite on spinning disks & 4G SD cards a long time ago, cpu idle and disk 100% busy, and it was taking days/weeks). 

Also blaming the lack of multicore support on disk IO bringing down PCs is moot. Spinning disk breaks, that's a fact, but it's usually a mechanical failure and not necessarily connected to disk IO, although using the disk is the only way you can notice the problem. My cheap sata RAID1 has been running a constant IO-bound load since I brought it up over a year ago and it has yet to show any sign of failures, while I've seen totally idle disks crash (in one case the computer stayed up for months after the disks went out of order since it was not doing anything - the computer was up but all io attempts failing, a reboot obviously brought it hard down).

**Comment by Safihre** [comment]
@BlackIkeEagle 
Why not include par2cmdline-mt's changes, **but** set the default number of cores to 1?
The code changes by @jkansanen are simple and straightforward:
https://github.com/Parchive/par2cmdline/compare/master...jkansanen:master

**Comment by BlackIkeEagle** [comment]
par2cmdline-mt is now merged
