### ISSUE TITLE
Enable -N by default? 

### ISSUE THREAD

**Issue by Safihre** [Parchive/par2cmdline#65]
In sabnzbd we always recommend par2cmdline for Linux systems and it has been working great, thank you for your continued work on this project :) 

Lately we have been getting more and more reports of people's repair failing on their download system for lack of blocks, but then when they repair it on another system with quickpar or par2tbb it repairs fine. 
We narrowed it down to the introduction of this -N parameter, which seems to solve the issue. 
We ran multiple tests and enabling this -N parameter by default doesn't seem to slow down verification at all? 
We were wondering why this was separated? 

We will now have to build in a check to see if the installed version of par2cmdline supports this -N and then add it. That will work, but is kind of hackish.

**Comment by BlackIkeEagle** [comment]
@Safihre the data skipping was introduced because you can DOS par2cmdline with malciously crafted par files where it would take forever to repair.

If you could provide a sample where you have to use -N to repair I can look into it.

**Comment by Safihre** [comment]
Aaah now I understand :) 
We have user reports on our forums, but hard to find one myself where it actually made the difference between successful restore or not because on Windows sabnzbd defaults to par2tbb.
But quite often there is a few blocks difference, but usually the file is then too damaged to be repaired anyway. 
Will get back to you when I have a dataset!

**Comment by sanderjo** [comment]
See https://forums.sabnzbd.org/viewtopic.php?f=2&t=19998#p103719 for an example.

I will upload such a sample to Dropbox, and share the link

**Comment by BlackIkeEagle** [comment]
@sanderjo thanks I'll have a look

**Comment by sanderjo** [comment]
FWIW: par2's output ```If there are not enough blocks found to repair: try again with the -N option.``` makes me think par2 itself does know the -N option can repair more. Correct?

**Comment by BlackIkeEagle** [comment]
@sanderjo to avoid the DOS there are blocks skipped. So yes par2 is aware there might be false positives in the detection of the DOS situation

**Comment by Safihre** [comment]
@shypike since this extra line in the par2 output (see @sanderjo post above) is only posted when the par2cmdline version supports -N and it is not turned on, we could display an error or other message only when there's not a crazy amount of blocks missing? Informing them that they can input the -N and try again?

**Comment by shypike** [comment]
@Safihre hmm, and head for a potential DDOS? -N is not a per-job setting.

**Comment by Safihre** [comment]
I know this is not an argument, but still: we supply DDOS volunerable par2tbb with *all* Windows and OSX installations...

**Comment by sanderjo** [comment]
@BlackIkeEagle Is https://github.com/Parchive/par2cmdline/issues/65#issuecomment-174165355 as it should be, or can it be solved/improved within par2?

If par2 cannot improve that: 
@shypike @Safihre How about this approach from within SABnzbd ( @BlackIkeEagle , let it know if you don't want this discussion here):

Let SABnzbd run par2 without -N. If par2 is able to repair the files, we're done.
If par2 does not succeed and par2 says "If there are not enough blocks found to repair: try again with the -N option." ... let's do that: run par2 again, now with -N. SABnzbd should now monitor par2 ... if it stalls (of example: no new par2 stdout output within 5 minutes or so), SABnzbd should terminate it.

@BlackIkeEagle are those DOS-files (2mb_0s.bin, 2mb_col.bin, pattern16.bin) available so that I can verify the above approach?

**Comment by shypike** [comment]
@Safihre Could be possible. Most of the logic is already present, in the form of retrying with "classic". 
(Although that was to account for some other bugs in par2-tbb which required a re-run with "classic". And also because par2-tbb assumes UTF8 file names, while "classic" assumes CP-1252.)
It's a can of worms, into which I must delve again.

**Comment by BlackIkeEagle** [comment]
@sanderjo I've added the collission files a while back

I'm also thinking of changing back to the before behaviour because the DOS is kindof an edgecase.

So I will probably change -N to "run par2 with the collision check" and default as before.

**Comment by Safihre** [comment]
:+1:

**Comment by BlackIkeEagle** [comment]
-N behaviour is now inverted
