### ISSUE TITLE
Make Homebrew formula

### ISSUE THREAD

**Issue by ujay68** [Parchive/par2cmdline#72]
There is a Homebrew formula for installing par2cmdline on OS X, but it points to the stale SourceForge project, see https://github.com/Homebrew/homebrew-core/blob/master/Formula/par2.rb 

It would be nice to have a formula for the active branch here.

**Comment by BlackIkeEagle** [comment]
@ujay68 could you open a pull request against the homebrew repo? I don't have osx so I can't really test it, travis reports its working :)

**Comment by ujay68** [comment]
OK, I'll see what I can do. I don't have experience in creating brew formulas. Shouldn't be too hard though.

**Comment by ujay68** [comment]
The Homebrew team asks whether the branch here is "blessed" by the original developer as the official successor. Is it?

https://groups.google.com/d/msg/homebrew-discuss/ZNPNoHfQb-0/BSuDvWrKAQAJ

**Comment by BlackIkeEagle** [comment]
I think it is the official successor and the original maintainer also contributed here already.
see: https://github.com/Parchive/par2cmdline/commit/d5c903316873ae3a93805c26463cc23eabca13c4

There was a plan to migrate the par website from sourceforge but I've never received the backup to put it here.

**Comment by PeterBClements** [comment]
Yes, this repository on github is now the primary repository for par2cmdline.

Peter

**Comment by garybernhardt** [comment]
I submitted a pull request to Homebrew updating it to 0.6.14 (homebrew/homebrew-core#10572), which has now been merged. It required a patch to work around some BSD-incompatible dd flags, but was otherwise straightforward. (Those dd flags have already been fixed here in 855f3096c9f52cd0fbdb9e237c6c9624f7b90ea6, but no release has been cut since then.) This issue can be closed.

**Comment by BlackIkeEagle** [comment]
@garybernhardt thanks for putting in the work
